[package]
name = "regex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dot = "0.1.4"
graphviz-rust = "0.3.0"

# [profile.test]
# opt-level = 3

[profile.release]
debug = true
